### ISSUE TITLE
Дополнительные типы

### ISSUE THREAD

**Issue by VZhyrytskiy** [ivanina-ilya/A2-11-shop#1]
Я думаю, что создав дополнительные типы, вы немного уменьшили читаемость кода. Но смотрите сами, можно их убрать, можно оставить. 
Я бы использовал вместо
private products: ProductMapType[] = new Array();
вот такой вариант
private products: Product[];

**Comment by ivanina-ilya** [comment]
Спасибо!
"ProductMapType[]" - исправил, заменил.

В отношении дополнительных типов не могу полностью согласиться, потому как они обеспечивают корректность данных и использования переменных.

- CounterType задает индекс обязательно как строка, а значение - как число. необходимо для хранения количества товара по SKU

- ProductMapType преследует такую же цель, только для хранения набора продуктов (SKU -> Product)

стоит ли организовать эти типы в отдельную директорию?

**Comment by VZhyrytskiy** [comment]
Разве это то, что вам нужно?
export interface CounterType {
    [index: string]: number;
}
const a: CounterType = {};
a.f1 = 10;
a.f2 = 20;
Такой тип не гарантирует, что у вас в объекте будет одна пара. Их может быть сколько угодно.

**Comment by ivanina-ilya** [comment]
Да, именно такую цель проследовал: создать массив в котором ключом может быть только строка и ничего более (это будет SKU), а значением будет только число - количество товара на складе.
Пара "ключ-строка" --- "значение-число" и будет являться этим типом (CounterType )
Как пример:
inStore: CounterType[] = new Array();

==>
inStore[ CounterType, CounterType, CounterType]

==>
inStore[
    string: number,
    string: number,
    string: number,
]

and as result with data:
inStore [
    '81BF00EFRA':        1,
    'FX553VE-DM406': 3,
    '81BF00EFRA':        0
]

Наверно для этого задания не нужно такой строгой типизации. Это вы имели в виду?

**Comment by VZhyrytskiy** [comment]
Я что-то не понял
Пазве это валидный код
inStore [
'81BF00EFRA': 1,
'FX553VE-DM406': 3,
'81BF00EFRA': 0
]
Я понял так, что тип CounterType должен по вашему замыслу описывать объект, в котором есть строчный ключ и числовое значение и все. Но, таких пар у объекта может быть сколько угодно. 
Например,
const a: CounterType = {};
const b: CounterType = { f1: 10};
const c: CounterType = { f1: 10, f2: 20};
...
inStore: CounterType[] = new Array();
inStore.push(a, b, c);
Этот тип не гарантирует, что пара ключ/значение будет одна. Если это вам и нужно, тогда ок, если нет, то обратите на это внимание.

**Comment by ivanina-ilya** [comment]
Спасибо за ваше включение и комментарий.
Этот фрагмент:
`inStore [
    '81BF00EFRA':        1,
    'FX553VE-DM406': 3,
    '81BF00EFRA':        0
]`
конечно же не является валидным кодом. Он предоставляет наглядный пример структуры данных.
**inStore** здесь представлена типом  **CounterType[]**

Но Вас я понял. Такая структура данных не гарантирует хранения валидных данных, так как можно создать что-то вроде такого (опять же это пример структуры, а не валидный код):
`inStore [
    '81BF00EFRA':        1,
   { 'FX553VE-DM406': 3, 'something-else': 10 },
    '81BF00EFRA':        0
]`

Спасибо за замечание. В следующей реализации я пересмотрю этот подход.
