### ISSUE TITLE
products.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [ivanina-ilya/A2-11-shop#2]
Не понял я зачем вы усложнили логику методом this.productsService.init();
Заведите публичное свойство products и проинициализируйте его в методе ngOnInit с помощью this.productsService.getProductList(); и из сервиса убрать можно флаг.

**Comment by ivanina-ilya** [comment]
Согласен, спасибо.
Переместил инициализацию списка продуктов в core-store-service, как часть логики коммуникации с back-end (получение списка продуктов с внешнего хранилища)
