### ISSUE TITLE
Директива

### ISSUE THREAD

**Issue by VZhyrytskiy** [ivanina-ilya/A2-11-shop#3]
Директиву надо повесить на HTML элемент
div mouseOverHighlight="red"
  <div>SKU: {{product.sku}}</div>
  <div>{{product.title}}</div>
  <div>{{product.price | currency}}</div>
  <div>(in stock: {{inStock()}})</div>
  <app-add-to-cart [product]="product"></app-add-to-cart>
/div

Если она подключена в AppModule, то это не значит, что она доступна компонентам ProductsModule. Ее необходимо оформить в SharedModule и подключать там, где она нужна.

**Comment by ivanina-ilya** [comment]
Спасибо!
Оформил через Shared Module
