### ISSUE TITLE
cart.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [ivanina-ilya/A2-11-shop#4]
Не очень понял, что значит new Error(...) может оператор throw пропущен?

removeFromCart(sku: string, count?: number): number {
    if( typeof count === 'undefined' ) { count = 1;}
    let counter: Counter = this.getInCart(sku);
    if( counter === undefined ) { new Error(`The product with SKU '${sku}' is missing in Cart`); }
    if( counter.count < count ) {
      new Error(`The ${count} product(s) with SKU '${sku}' is not available in cart (${counter.count})`);
    }

**Comment by ivanina-ilya** [comment]
Спасибо, что обратили внимание - кончено пропущен throw.
Исправил
